#!/usr/bin/sh

# Small program that prints out 1 of 21 principles found in Miyamoto Musashi's
# 'The Path of Aloneness' (Dokkodo). Ref. https://en.wikipedia.org/wiki/Dokkodo

r=$(shuf -i 1-21 -n 1)

case $r in
1) echo "1. Accept everything just the way it is." ;;
2) echo "2. Do not seek pleasure for its own sake." ;;
3) echo "3. Do not, under any circumstances, depend on a partial feeling." ;;
4) echo "4. Think lightly of yourself and deeply of the world." ;;
5) echo "5. Be detached from desire your whole life long." ;;
6) echo "6. Do not regret what you have done." ;;
7) echo "7. Never be jealous." ;;
8) echo "8. Never let yourself be saddened by a separation." ;;
9) echo "9. Resentment and complaint are appropriate neither for oneself nor others." ;;
10) echo "10. Do not let yourself be guided by the feeling of lust or love." ;;
11) echo "11. In all things have no preferences." ;;
12) echo "12. Be indifferent to where you live." ;;
13) echo "13. Do not pursue the taste of good food." ;;
14) echo "14. Do not hold on to possessions you no longer need." ;;
15) echo "15. Do not act following customary beliefs." ;;
16) echo "16. Do not collect weapons or practice with weapons beyond what is useful." ;;
17) echo "17. Do not fear death." ;;
18) echo "18. Do not seek to possess either goods or fiefs for your old age." ;;
19) echo "19. Respect Buddha and the gods without counting on their help." ;;
20) echo "20. You may abandon your own body but you must preserve your honor." ;;
21) echo "21. Never stray from the Way." ;;
esac
